import { BaseComponent } from "utilities_js";
import { ImgAvatar, PeopleBlack } from "../../assets";

export interface IProps {
  location: any;
  navigate?: any;
  myusername?: boolean;

}
export interface IState {
  friends: any[];
  isShow: number;
  group: any[];
  isFocus: boolean;
  inputValue: string;
  searched: any;
  isShowGroup: number;
  userGroups: any[];
  friendsSearch: any[];
  groupSearch: any[];
}

class ChatController extends BaseComponent<IProps, IState> {
  state = {
    isShow: 0,
    inputValue: "",
    isFocus: false,
    friends: [
      {
        to: "#",
        name: "سمانه احمدیان",
        username: "samanehahmadian",
        avatar: ImgAvatar,
        messages: [
          {
            id: 1,
            type: "recive",
            text: "سلام خوبی پس این چی شد",
            date: "1401/2/1",
          },
          { id: 2, type: "recive", text: "من هنوز منتظر هستم !!!" },
          {
            id: 3,
            type: "send",
            text: "سلام ، کی آنلاین میشی ؟",
            date: "1401/2/2",
          },
          { id: 4, type: "recive", text: "سلام ، کی آنلاین میشی ؟" },
          { id: 5, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 6, type: "", text: "اولین فرصت خبر می دم خدمتتون" },
        ],
        isSeen: false,
        numOfNotSeen: 10,
        id: 1,
      },
      {
        to: "#",
        name: "مجید محرمی",
        username: "majidmoharami",
        avatar: ImgAvatar,
        messages: [
          {
            id: 1,
            type: "recive",
            text: "سلام خوبی پس این چی شد",
            date: "1401/2/1",
          },
          { id: 2, type: "recive", text: "من هنوز منتظر هستم !!!" },
          {
            id: 3,
            type: "send",
            text: "سلام ببخشید در اولین فرصت اقدام می کنم.",
            date: "1401/2/2",
          },
          { id: 4, type: "recive", text: "ممنون از شما" },
          { id: 5, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 6, type: "recive", text: "اولین فرصت خبر می دم خدمتتون" },
          { id: 7, type: "recive", text: "منتظر خبرتون هستم" },
        ],
        isSeen: true,
        numOfNotSeen: 0,

        id: 2,
      },
      {
        to: "#",
        name: "محمد جواد ابراهیمی",
        username: "ebram",
        avatar: ImgAvatar,
        messages: [
          {
            id: 1,
            type: "recive",
            text: "سلام خوبی پس این چی شد",
            date: "1401/2/1",
          },
          { id: 2, type: "recive", text: "من هنوز منتظر هستم !!!" },
          {
            id: 3,
            type: "send",
            text: "سلام ببخشید در اولین فرصت اقدام می کنم.",
            date: "1401/2/2",
          },
          { id: 4, type: "recive", text: "ممنون از شما" },
          { id: 5, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 6, type: "recive", text: "اولین فرصت خبر می دم خدمتتون" },
          { id: 7, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 8, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 9, type: "recive", text: "منتظر خبرتون هستم" },
        ],
        isSeen: false,
        numOfNotSeen: 3,

        id: 3,
      },
      {
        to: "#",
        name: "عباس مجیدی",
        username: "abbas",
        avatar: ImgAvatar,
        messages: [
          {
            id: 1,
            type: "recive",
            text: "سلام خوبی پس این چی شد",
            date: "1401/2/1",
          },
          { id: 2, type: "recive", text: "من هنوز منتظر هستم !!!" },
          {
            id: 3,
            type: "send",
            text: "سلام ببخشید در اولین فرصت اقدام می کنم.",
            date: "1401/2/2",
          },
          { id: 4, type: "recive", text: "ممنون از شما" },
          { id: 5, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 6, type: "recive", text: "اولین فرصت خبر می دم خدمتتون" },
          { id: 7, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 8, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 9, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 10, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 11, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 12, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 13, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 14, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 15, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 16, type: "recive", text: "منتظر خبرتون هستم" },
        ],
        isSeen: true,
        numOfNotSeen: 0,

        id: 4,
      },
    ],

    group: [
      {
        username: "spelendor",
        name: "متعصبین اسپلندور",
        avatar: PeopleBlack,
        messages: [
          {
            id: 1,
            type: "recive",
            text: "سلام خوبی پس این چی شد",
            date: "1401/2/1",
          },
          { id: 2, type: "recive", text: "من هنوز منتظر هستم !!!" },
          {
            id: 3,
            type: "send",
            text: "سلام ببخشید در اولین فرصت اقدام می کنم.",
            date: "1401/2/2",
          },
          { id: 4, type: "recive", text: "ممنون از شما" },
          { id: 5, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 6, type: "", text: "اولین فرصت خبر می دم خدمتتون" },
        ],
        isSeen: false,
        isRequest: false,
        isJoin: true,
        numOfNotSeen: "3",
        id: 1,
      },
      {
        username: "sspelen2dorr",
        name: "بچه های شمرون",
        avatar: PeopleBlack,
        messages: [
          {
            id: 1,
            type: "recive",
            text: "سلام خوبی پس این چی شد",
            date: "1401/2/1",
          },
          { id: 2, type: "recive", text: "من هنوز منتظر هستم !!!" },
          {
            id: 3,
            type: "send",
            text: "سلام ببخشید در اولین فرصت اقدام می کنم.",
            date: "1401/2/2",
          },
          { id: 4, type: "recive", text: "ممنون از شما" },
          { id: 5, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 6, type: "recive", text: "اولین فرصت خبر می دم خدمتتون" },
          { id: 7, type: "recive", text: "منتظر خبرتون هستم" },
        ],
        isSeen: false,
        isRequest: false,
        isJoin: true,
        numOfNotSeen: "121",
        id: 2,
      },
      {
        username: "sppelendor",

        name: "دوئل بازای قدیمی",
        avatar: PeopleBlack,
        messages: [
          {
            id: 1,
            type: "recive",
            text: "سلام خوبی پس این چی شد",
            date: "1401/2/1",
          },
          { id: 2, type: "recive", text: "من هنوز منتظر هستم !!!" },
          {
            id: 3,
            type: "send",
            text: "سلام ببخشید در اولین فرصت اقدام می کنم.",
            date: "1401/2/2",
          },
          { id: 4, type: "recive", text: "ممنون از شما" },
          { id: 5, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 6, type: "recive", text: "اولین فرصت خبر می دم خدمتتون" },
          { id: 7, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 8, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 9, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 10, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 11, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 12, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 13, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 14, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 15, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 16, type: "recive", text: "منتظر خبرتون هستم" },
        ],
        isSeen: false,
        isRequest: false,
        isJoin: true,
        numOfNotSeen: "22",
        id: 3,
      },
      {
        username: "speelendor",

        name: " اسپلندور شب جمعه ها",
        avatar: PeopleBlack,
        messages: [
          {
            id: 1,
            type: "recive",
            text: "سلام خوبی پس این چی شد",
            date: "1401/2/1",
          },
          { id: 2, type: "recive", text: "من هنوز منتظر هستم !!!" },
          {
            id: 3,
            type: "send",
            text: "سلام ببخشید در اولین فرصت اقدام می کنم.",
            date: "1401/2/2",
          },
          { id: 4, type: "recive", text: "ممنون از شما" },
          { id: 5, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 6, type: "recive", text: "اولین فرصت خبر می دم خدمتتون" },
          { id: 7, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 8, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 9, type: "recive", text: "منتظر خبرتون هستم" },
        ],
        isSeen: true,
        isRequest: false,
        isJoin: true,
        numOfNotSeen: "0",
        id: 4,
      },
      {
        username: "spellendor",

        name: "پسرخاله ها و دختر خاله های خاندان ...",
        avatar: PeopleBlack,
        messages: [
          { id: 1, text: "سلام" },
          { id: 2, text: "خوبی" },
          { id: 3, text: "چطوری" },
          { id: 4, text: "سلام ، کی آنلاین میشی ؟" },
        ],
        isSeen: true,
        isRequest: false,
        isJoin: true,
        numOfNotSeen: "0",
        id: 5,
      },
      {
        username: "speleendor",
        name: " دوستای قدیمی",
        avatar: PeopleBlack,
        messages: [
          { id: 1, text: "سلام" },
          { id: 2, text: "خوبی" },
          { id: 3, text: "چطوری" },
          { id: 4, text: "سلام ، کی آنلاین میشی ؟" },
          { id: 5, text: "چطوری" },
          { id: 6, text: "چطوری" },
          { id: 7, text: "چطوری" },
          { id: 8, text: "چطوری" },
        ],
        isSeen: true,
        isRequest: false,
        isJoin: true,
        numOfNotSeen: "0",
        id: 6,
      },
      {
        username: "spelenndor",
        name: " دوستای قدیمی",
        avatar: PeopleBlack,
        messages: [
          { id: 1, text: "سلام" },
          { id: 2, text: "خوبی" },
          { id: 3, text: "چطوری" },
          { id: 4, text: "سلام ، کی آنلاین میشی ؟" },
          { id: 5, text: "چطوری" },
          { id: 6, text: "چطوری" },
          { id: 7, text: "چطوری" },
          { id: 8, text: "سلام" },
        ],
        isSeen: true,
        isRequest: false,
        isJoin: true,
        numOfNotSeen: "0",
        id: 7,
      },
      {
        username: "spelenddor",
        name: " دوستای قدیمی",
        avatar: PeopleBlack,
        messages: [
          { id: 1, text: "سلام" },
          { id: 2, text: "خوبی" },
          { id: 3, text: "چطوری" },
          { id: 4, text: "سلام ، کی آنلاین میشی ؟" },
          { id: 5, text: "چطوری" },
          { id: 6, text: "چطوری" },
          { id: 7, text: "چطوری" },
          { id: 8, text: "چطوری" },
        ],
        isSeen: true,
        isRequest: false,
        isJoin: true,
        numOfNotSeen: "0",
        id: 8,
      },
      {
        username: "spelendoor",
        name: " دوستای قدیمی",
        avatar: PeopleBlack,
        messages: [
          { id: 1, text: "سلام" },
          { id: 2, text: "خوبی" },
          { id: 3, text: "چطوری" },
          { id: 4, text: "سلام ، کی آنلاین میشی ؟" },
          { id: 5, text: "چطوری" },
          { id: 6, text: "چطوری" },
          { id: 7, text: "چطوری" },
          { id: 8, text: "چطوری" },
        ],
        isSeen: true,
        isRequest: false,
        isJoin: true,
        numOfNotSeen: "0",
        id: 9,
      },
      {
        username: "spelendorr",
        name: " دوستای قدیمی",
        avatar: PeopleBlack,
        messages: [
          { id: 1, text: "سلام" },
          { id: 2, text: "خوبی" },
          { id: 3, text: "چطوری" },
          { id: 4, text: "سلام ، کی آنلاین میشی ؟" },
          { id: 5, text: "چطوری" },
          { id: 6, text: "چطوری" },
          { id: 7, text: "چطوری" },
          { id: 8, text: "چطوری" },
        ],
        isSeen: true,
        isRequest: false,
        isJoin: true,
        numOfNotSeen: "0",
        id: 10,
      },
    ],
    searched: [],
    isShowGroup: 0,
    userGroups: [
      {
        name: "متعصبین اسپلندور",
        avatar: PeopleBlack,
        messages: [
          { id: 1, text: "سلام" },
          { id: 2, text: "خوبی" },
          { id: 3, text: "چطوری" },
          { id: 4, text: "سلام ، کی آنلاین میشی ؟" },
        ],
        isSeen: false,
        isRequest: false,
        isJoin: false,
        numOfNotSeen: "3",
        id: 1,
      },
      {
        name: "بچه های شمرون",
        avatar: PeopleBlack,
        messages: [
          { id: 1, text: "سلام" },
          { id: 2, text: "خوبی" },
          { id: 3, text: "چطوری" },
          { id: 4, text: "سلام ، کی آنلاین میشی ؟" },
        ],
        isSeen: false,
        isRequest: false,
        isJoin: true,
        numOfNotSeen: "121",
        id: 2,
      },
      {
        name: "دوئل بازای قدیمی",
        avatar: PeopleBlack,
        messages: [
          { id: 1, text: "سلام" },
          { id: 2, text: "خوبی" },
          { id: 3, text: "چطوری" },
          { id: 4, text: "سلام ، کی آنلاین میشی ؟" },
        ],
        isSeen: false,
        isRequest: true,
        isJoin: false,
        numOfNotSeen: "22",
        id: 3,
      },
      {
        name: " اسپلندور شب جمعه ها",
        avatar: PeopleBlack,
        messages: [
          { id: 1, text: "سلام" },
          { id: 2, text: "خوبی" },
          { id: 3, text: "چطوری" },
          { id: 4, text: "سلام ، کی آنلاین میشی ؟" },
        ],
        isSeen: true,
        isRequest: true,
        isJoin: false,
        numOfNotSeen: "0",
        id: 4,
      },
      {
        name: "پسرخاله ها و دختر خاله های خاندان ...",
        avatar: PeopleBlack,
        messages: [
          { id: 1, text: "سلام" },
          { id: 2, text: "خوبی" },
          { id: 3, text: "چطوری" },
          { id: 4, text: "سلام ، کی آنلاین میشی ؟" },
        ],
        isSeen: true,
        isRequest: false,
        isJoin: true,
        numOfNotSeen: "0",
        id: 5,
      },
      {
        name: " دوستای قدیمی",
        avatar: PeopleBlack,
        messages: [
          { id: 1, text: "سلام" },
          { id: 2, text: "خوبی" },
          { id: 3, text: "چطوری" },
          { id: 4, text: "سلام ، کی آنلاین میشی ؟" },
        ],
        isSeen: true,
        isRequest: false,
        isJoin: true,
        numOfNotSeen: "0",
        id: 6,
      },
    ],
    friendsSearch: [
      {
        to: "#",
        name: "سمانه احمدیان",
        username: "samanehahmadian",
        avatar: ImgAvatar,
        messages: [
          {
            id: 1,
            type: "recive",
            text: "سلام خوبی پس این چی شد",
            date: "1401/2/1",
          },
          { id: 2, type: "recive", text: "من هنوز منتظر هستم !!!" },
          {
            id: 3,
            type: "send",
            text: "سلام ، کی آنلاین میشی ؟",
            date: "1401/2/2",
          },
          { id: 4, type: "recive", text: "سلام ، کی آنلاین میشی ؟" },
          { id: 5, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 6, type: "", text: "اولین فرصت خبر می دم خدمتتون" },
        ],
        isSeen: false,
        numOfNotSeen: 10,
        id: 1,
      },
      {
        to: "#",
        name: "مجید محرمی",
        username: "majidmoharami",
        avatar: ImgAvatar,
        messages: [
          {
            id: 1,
            type: "recive",
            text: "سلام خوبی پس این چی شد",
            date: "1401/2/1",
          },
          { id: 2, type: "recive", text: "من هنوز منتظر هستم !!!" },
          {
            id: 3,
            type: "send",
            text: "سلام ببخشید در اولین فرصت اقدام می کنم.",
            date: "1401/2/2",
          },
          { id: 4, type: "recive", text: "ممنون از شما" },
          { id: 5, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 6, type: "recive", text: "اولین فرصت خبر می دم خدمتتون" },
          { id: 7, type: "recive", text: "منتظر خبرتون هستم" },
        ],
        isSeen: true,
        numOfNotSeen: 0,

        id: 2,
      },
      {
        to: "#",
        name: "محمد جواد ابراهیمی",
        username: "ebram",
        avatar: ImgAvatar,
        messages: [
          {
            id: 1,
            type: "recive",
            text: "سلام خوبی پس این چی شد",
            date: "1401/2/1",
          },
          { id: 2, type: "recive", text: "من هنوز منتظر هستم !!!" },
          {
            id: 3,
            type: "send",
            text: "سلام ببخشید در اولین فرصت اقدام می کنم.",
            date: "1401/2/2",
          },
          { id: 4, type: "recive", text: "ممنون از شما" },
          { id: 5, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 6, type: "recive", text: "اولین فرصت خبر می دم خدمتتون" },
          { id: 7, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 8, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 9, type: "recive", text: "منتظر خبرتون هستم" },
        ],
        isSeen: false,
        numOfNotSeen: 3,

        id: 3,
      },
      {
        to: "#",
        name: "عباس مجیدی",
        username: "abbas",
        avatar: ImgAvatar,
        messages: [
          {
            id: 1,
            type: "recive",
            text: "سلام خوبی پس این چی شد",
            date: "1401/2/1",
          },
          { id: 2, type: "recive", text: "من هنوز منتظر هستم !!!" },
          {
            id: 3,
            type: "send",
            text: "سلام ببخشید در اولین فرصت اقدام می کنم.",
            date: "1401/2/2",
          },
          { id: 4, type: "recive", text: "ممنون از شما" },
          { id: 5, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 6, type: "recive", text: "اولین فرصت خبر می دم خدمتتون" },
          { id: 7, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 8, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 9, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 10, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 11, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 12, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 13, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 14, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 15, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 16, type: "recive", text: "منتظر خبرتون هستم" },
        ],
        isSeen: true,
        numOfNotSeen: 0,

        id: 4,
      },
    ],
    groupSearch: [
      {
        username: "spelendor",
        name: "متعصبین اسپلندور",
        avatar: PeopleBlack,
        messages: [
          {
            id: 1,
            type: "recive",
            text: "سلام خوبی پس این چی شد",
            date: "1401/2/1",
          },
          { id: 2, type: "recive", text: "من هنوز منتظر هستم !!!" },
          {
            id: 3,
            type: "send",
            text: "سلام ببخشید در اولین فرصت اقدام می کنم.",
            date: "1401/2/2",
          },
          { id: 4, type: "recive", text: "ممنون از شما" },
          { id: 5, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 6, type: "", text: "اولین فرصت خبر می دم خدمتتون" },
        ],
        isSeen: false,
        isRequest: false,
        isJoin: true,
        numOfNotSeen: "3",
        id: 1,
      },
      {
        username: "sspelen2dorr",
        name: "بچه های شمرون",
        avatar: PeopleBlack,
        messages: [
          {
            id: 1,
            type: "recive",
            text: "سلام خوبی پس این چی شد",
            date: "1401/2/1",
          },
          { id: 2, type: "recive", text: "من هنوز منتظر هستم !!!" },
          {
            id: 3,
            type: "send",
            text: "سلام ببخشید در اولین فرصت اقدام می کنم.",
            date: "1401/2/2",
          },
          { id: 4, type: "recive", text: "ممنون از شما" },
          { id: 5, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 6, type: "recive", text: "اولین فرصت خبر می دم خدمتتون" },
          { id: 7, type: "recive", text: "منتظر خبرتون هستم" },
        ],
        isSeen: false,
        isRequest: false,
        isJoin: true,
        numOfNotSeen: "121",
        id: 2,
      },
      {
        username: "sppelendor",

        name: "دوئل بازای قدیمی",
        avatar: PeopleBlack,
        messages: [
          {
            id: 1,
            type: "recive",
            text: "سلام خوبی پس این چی شد",
            date: "1401/2/1",
          },
          { id: 2, type: "recive", text: "من هنوز منتظر هستم !!!" },
          {
            id: 3,
            type: "send",
            text: "سلام ببخشید در اولین فرصت اقدام می کنم.",
            date: "1401/2/2",
          },
          { id: 4, type: "recive", text: "ممنون از شما" },
          { id: 5, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 6, type: "recive", text: "اولین فرصت خبر می دم خدمتتون" },
          { id: 7, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 8, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 9, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 10, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 11, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 12, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 13, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 14, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 15, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 16, type: "recive", text: "منتظر خبرتون هستم" },
        ],
        isSeen: false,
        isRequest: false,
        isJoin: true,
        numOfNotSeen: "22",
        id: 3,
      },
      {
        username: "speelendor",

        name: " اسپلندور شب جمعه ها",
        avatar: PeopleBlack,
        messages: [
          {
            id: 1,
            type: "recive",
            text: "سلام خوبی پس این چی شد",
            date: "1401/2/1",
          },
          { id: 2, type: "recive", text: "من هنوز منتظر هستم !!!" },
          {
            id: 3,
            type: "send",
            text: "سلام ببخشید در اولین فرصت اقدام می کنم.",
            date: "1401/2/2",
          },
          { id: 4, type: "recive", text: "ممنون از شما" },
          { id: 5, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 6, type: "recive", text: "اولین فرصت خبر می دم خدمتتون" },
          { id: 7, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 8, type: "recive", text: "منتظر خبرتون هستم" },
          { id: 9, type: "recive", text: "منتظر خبرتون هستم" },
        ],
        isSeen: true,
        isRequest: false,
        isJoin: true,
        numOfNotSeen: "0",
        id: 4,
      },
      {
        username: "spellendor",

        name: "پسرخاله ها و دختر خاله های خاندان ...",
        avatar: PeopleBlack,
        messages: [
          { id: 1, text: "سلام" },
          { id: 2, text: "خوبی" },
          { id: 3, text: "چطوری" },
          { id: 4, text: "سلام ، کی آنلاین میشی ؟" },
        ],
        isSeen: true,
        isRequest: false,
        isJoin: true,
        numOfNotSeen: "0",
        id: 5,
      },
      {
        username: "speleendor",
        name: " دوستای قدیمی",
        avatar: PeopleBlack,
        messages: [
          { id: 1, text: "سلام" },
          { id: 2, text: "خوبی" },
          { id: 3, text: "چطوری" },
          { id: 4, text: "سلام ، کی آنلاین میشی ؟" },
          { id: 5, text: "چطوری" },
          { id: 6, text: "چطوری" },
          { id: 7, text: "چطوری" },
          { id: 8, text: "چطوری" },
        ],
        isSeen: true,
        isRequest: false,
        isJoin: true,
        numOfNotSeen: "0",
        id: 6,
      },
      {
        username: "spelenndor",
        name: " دوستای قدیمی",
        avatar: PeopleBlack,
        messages: [
          { id: 1, text: "سلام" },
          { id: 2, text: "خوبی" },
          { id: 3, text: "چطوری" },
          { id: 4, text: "سلام ، کی آنلاین میشی ؟" },
          { id: 5, text: "چطوری" },
          { id: 6, text: "چطوری" },
          { id: 7, text: "چطوری" },
          { id: 8, text: "سلام" },
        ],
        isSeen: true,
        isRequest: false,
        isJoin: true,
        numOfNotSeen: "0",
        id: 7,
      },
      {
        username: "spelenddor",
        name: " دوستای قدیمی",
        avatar: PeopleBlack,
        messages: [
          { id: 1, text: "سلام" },
          { id: 2, text: "خوبی" },
          { id: 3, text: "چطوری" },
          { id: 4, text: "سلام ، کی آنلاین میشی ؟" },
          { id: 5, text: "چطوری" },
          { id: 6, text: "چطوری" },
          { id: 7, text: "چطوری" },
          { id: 8, text: "چطوری" },
        ],
        isSeen: true,
        isRequest: false,
        isJoin: true,
        numOfNotSeen: "0",
        id: 8,
      },
      {
        username: "spelendoor",
        name: " دوستای قدیمی",
        avatar: PeopleBlack,
        messages: [
          { id: 1, text: "سلام" },
          { id: 2, text: "خوبی" },
          { id: 3, text: "چطوری" },
          { id: 4, text: "سلام ، کی آنلاین میشی ؟" },
          { id: 5, text: "چطوری" },
          { id: 6, text: "چطوری" },
          { id: 7, text: "چطوری" },
          { id: 8, text: "چطوری" },
        ],
        isSeen: true,
        isRequest: false,
        isJoin: true,
        numOfNotSeen: "0",
        id: 9,
      },
      {
        username: "spelendorr",
        name: " دوستای قدیمی",
        avatar: PeopleBlack,
        messages: [
          { id: 1, text: "سلام" },
          { id: 2, text: "خوبی" },
          { id: 3, text: "چطوری" },
          { id: 4, text: "سلام ، کی آنلاین میشی ؟" },
          { id: 5, text: "چطوری" },
          { id: 6, text: "چطوری" },
          { id: 7, text: "چطوری" },
          { id: 8, text: "چطوری" },
        ],
        isSeen: true,
        isRequest: false,
        isJoin: true,
        numOfNotSeen: "0",
        id: 10,
      },
    ],
  };
  // componentDidUpdate() {
  //   console.log(this.state.friendsSearch);
  // }
}
export default ChatController;
