name: ReactJS CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          local-dir: build/
          server: anbor.SinaMN75.com
          username: Keyfoor_react
          password: BetterSoft1234!@#$
